services:
  planner.api:
    image: ${DOCKER_REGISTRY-}plannerapi
    build:
      context: .
      dockerfile: Planner.Api/Dockerfile
    depends_on:
      - postgres
    

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 100110
      POSTGRES_DB: Planner
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
   

volumes:
  postgres-data:
